[package]
name = "test-tracking"
version = "0.1.0"
edition = "2021"


[dependencies]

[target.aarch64-apple-darwin]
rustflags = ["-L./bindings/macos", "-lMouseMonitor"]

[alias]
dev = "watch -c -x run"